### ISSUE TITLE
Exception 500 on get artpiece

### ISSUE THREAD

**Issue by shnaseri** [AliBagherz/Negare_backend#17]
I/flutter (24052): <!DOCTYPE html>
I/flutter (24052): <html lang="en">
I/flutter (24052): <head>
I/flutter (24052):   <meta http-equiv="content-type" content="text/html; charset=utf-8">
I/flutter (24052):   <meta name="robots" content="NONE,NOARCHIVE">
I/flutter (24052):   <title>RelatedObjectDoesNotExist
I/flutter (24052):           at /api/art/art-piece/29/</title>
I/flutter (24052):   <style type="text/css">
I/flutter (24052):     html * { padding:0; margin:0; }
I/flutter (24052):     body * { padding:10px 20px; }
I/flutter (24052):     body * * { padding:0; }
I/flutter (24052):     body { font:small sans-serif; background-color:#fff; color:#000; }
I/flutter (24052):     body>div { border-bottom:1px solid #ddd; }
I/flutter (24052):     h1 { font-weight:normal; }
I/flutter (24052):     h2 { margin-bottom:.8em; }
I/flutter (24052):     h3 { margin:1em 0 .5em 0; }
I/flutter (24052):     h4 { margin:0 0 .5em 0; font-weight: normal; }
I/flutter (24052):     code, pre { font-size: 100%; white-space: pre-wrap; }
I/flutter (24052):     summary { cursor: pointer; }
I/flutter (24052):     table { border:1px solid #ccc; border-collapse: collapse; width:100%; background:white; }
I/flutter (24052):     tbody td, tbody th { vertical-align:top; padding:2px 3px; }
I/flutter (24052):     thead th {
I/flutter (24052):       padding:1px 6px 1px 3px; background:#fefefe; text-align:left;
I/flutter (24052):       font-weight:normal; font-size:11px; border:1px solid #ddd;
I/flutter (24052):   
I/flutter (24052): 500

**Comment by shnaseri** [comment]
@AliBagherz  jan ls check it

**Comment by AliBagherz** [comment]
fixed
